<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

return array(
'ExternalAccount_1' => array(
	'external_account_id' =>'96698fb8-bd4a-11e0-b684-00163e4c6b77',
	'external_account_datetime' =>'2011-08-02 17:01:26',
	'external_account_payment_profile_id' =>'eb01a3a8-1097-11e1-94cf-f23c91dfda4e',
	'external_account_type' => 'checking',
	'external_account_name' =>'Personal Checking',
	'external_account_bank' =>'First Test Bank',
	'external_account_holder' =>'John Doe',
	'external_account_country_code' =>'US',
	'external_account_dfi_id' =>'123456789',
	'external_account_dfi_id_qualifier' =>'01',
	'external_account_number' =>'11235813',
	'external_account_billing_address' =>'321 Cherry St.',
	'external_account_billing_city' =>'Anothertown',
	'external_account_billing_state_province' =>'KS',
	'external_account_billing_postal_code' =>'12346',
	'external_account_billing_country' =>'US',
	'external_account_business' =>0,
	'external_account_verification_status' =>'completed',
	'external_account_status' =>'enabled',
	'external_account_allow_originator_payments'=>false,
	'external_account_originator_info_id'=>'',
),
'ExternalAccount_2' => array(
	'external_account_id' =>'27e18302-d81b-11e0-ac5c-001a4b4851e2',
	'external_account_datetime' =>'2011-08-02 17:01:26',
	'external_account_payment_profile_id' =>'fbd32292-1097-11e1-94cf-f23c91dfda4e',
	'external_account_type' => 'checking',
	'external_account_name' =>'Business Checking',
	'external_account_bank' =>'First Test Bank',
	'external_account_holder' =>'John Doe',
	'external_account_country_code' =>'US',
	'external_account_dfi_id' =>'123456789',
	'external_account_dfi_id_qualifier' =>'01',
	'external_account_number' =>'11235814',
	'external_account_billing_address' =>'321 Cherry St.',
	'external_account_billing_city' =>'Anothertown',
	'external_account_billing_state_province' =>'KS',
	'external_account_billing_postal_code' =>'12346',
	'external_account_billing_country' =>'US',
	'external_account_business' =>1,
	'external_account_verification_status' =>'completed',
	'external_account_status' =>'enabled',
	'external_account_allow_originator_payments'=>false,
	'external_account_originator_info_id'=>'',
),
'ExternalAccount_3' => array(
	'external_account_id' =>'2c0b79dc-671e-11e1-83b4-f23c91dfda4e',
	'external_account_datetime' =>'2011-08-02 17:01:26',
	'external_account_payment_profile_id' =>'d1c891b6-5b9d-11e1-83b4-f23c91dfda4e',
	'external_account_type' => 'checking',
	'external_account_name' =>'Business Checking',
	'external_account_bank' =>'First Test Bank',
	'external_account_holder' =>'Alfonso Perez',
	'external_account_country_code' =>'US',
	'external_account_dfi_id' =>'123456789',
	'external_account_dfi_id_qualifier' =>'01',
	'external_account_number' =>'11235814',
	'external_account_billing_address' =>'321 Cherry St.',
	'external_account_billing_city' =>'Anothertown',
	'external_account_billing_state_province' =>'KS',
	'external_account_billing_postal_code' =>'12346',
	'external_account_billing_country' =>'US',
	'external_account_business' =>1,
	'external_account_verification_status' =>'completed',
	'external_account_status' =>'enabled',
	'external_account_allow_originator_payments'=>false,
	'external_account_originator_info_id'=>'',
),
'ExternalAccount_4' => array(
	'external_account_id' =>'2d0d15ca-671e-11e1-83b4-f23c91dfda4e',
	'external_account_datetime' =>'2011-08-02 17:01:26',
	'external_account_payment_profile_id' =>'c1d918c2-83b4-11e1-5b9d-1dfda4ef23c9',
	'external_account_type' => 'checking',
	'external_account_name' =>'Business Checking',
	'external_account_bank' =>'First Test Bank',
	'external_account_holder' =>'Hassan Firoozabadi',
	'external_account_country_code' =>'US',
	'external_account_dfi_id' =>'123456789',
	'external_account_dfi_id_qualifier' =>'01',
	'external_account_number' =>'11235814',
	'external_account_billing_address' =>'321 Cherry St.',
	'external_account_billing_city' =>'Anothertown',
	'external_account_billing_state_province' =>'KS',
	'external_account_billing_postal_code' =>'12346',
	'external_account_billing_country' =>'US',
	'external_account_business' =>1,
	'external_account_verification_status' =>'completed',
	'external_account_status' =>'enabled',
	'external_account_allow_originator_payments'=>false,
	'external_account_originator_info_id'=>'',
),
'ExternalAccount_5' => array(
	'external_account_id' =>'e049f556-f27a-4333-8d64-bc5d106c24bf',
	'external_account_datetime' =>'2011-08-02 17:01:26',
	'external_account_payment_profile_id' =>'',
	'external_account_type' => 'checking',
	'external_account_name' =>'Joes Diner GL Account',
	'external_account_bank' =>'US BANK NA',
	'external_account_holder' =>'Joes Diner',
	'external_account_country_code' =>'US',
	'external_account_dfi_id' =>'101000187',
	'external_account_dfi_id_qualifier' =>'01',
	'external_account_number' =>'1234567890',
	'external_account_billing_address' =>'321 Easy St.',
	'external_account_billing_city' =>'Anytown',
	'external_account_billing_state_province' =>'MO',
	'external_account_billing_postal_code' =>'12345',
	'external_account_billing_country' =>'US',
	'external_account_business' =>1,
	'external_account_verification_status' =>'completed',
	'external_account_status' =>'enabled',
	'external_account_allow_originator_payments'=>true,
	'external_account_originator_info_id'=>'4c5ad948-1c74-11e1-b7de-f23c91dfda4e',
),
);
