<?php
/*********************************************************************************
 * OpenACH is an ACH payment processing platform
 * Copyright (C) 2011 Steven Brendtro, ALL RIGHTS RESERVED
 * 
 * Refer to /legal/license.txt for license information, or view the full license
 * online at http://openach.com/community/license.txt
 ********************************************************************************/

return array(
	'sample1'=>array(
		'user_id' => '7b7e2a20-b78b-11e0-b684-00163e4c6b77',
		'user_login' => 'admin',
		'user_password' => sha1( 'admin' ),
		'user_first_name' => 'Test',
		'user_last_name' => 'Administrator',
		'user_email_address' => 'test-admin@openach.com',
		'user_security_question_1' => 'What is your favorite color?',
		'user_security_question_2' => 'What is capital of Assyria?',
		'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
		'user_security_answer_1' => 'Blue',
		'user_security_answer_2' => 'Nineveh',
		'user_security_answer_3' => 'African or European?',
		'user_status' => 'enabled',
	),
	'sample2'=>array(
		'user_id' => 'e3c90b32-b799-11e0-b684-00163e4c6b77',
		'user_login' => 'basic-user',
		'user_password' => sha1( 'basic-user' ),
		'user_first_name' => 'Basic',
		'user_last_name' => 'User',
		'user_email_address' => 'basic-user@openach.com',
		'user_security_question_1' => 'What is your favorite color?',
		'user_security_question_2' => 'What is capital of Assyria?',
		'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
		'user_security_answer_1' => 'Blue',
		'user_security_answer_2' => 'Nineveh',
		'user_security_answer_3' => 'African or European?',
		'user_status' => 'enabled',
	),
	'sample3'=>array(
		'user_id' => 'f0383de8-b799-11e0-b684-00163e4c6b77',
		'user_login' => 'advanced-user',
		'user_password' => sha1( 'advanced-user' ),
		'user_first_name' => 'Advanced',
		'user_last_name' => 'User',
		'user_email_address' => 'advanced-user@openach.com',
		'user_security_question_1' => 'What is your favorite color?',
		'user_security_question_2' => 'What is capital of Assyria?',
		'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
		'user_security_answer_1' => 'Blue',
		'user_security_answer_2' => 'Nineveh',
		'user_security_answer_3' => 'African or European?',
		'user_status' => 'enabled',
	),
        'sample4'=>array(
                'user_id' => '11383de8-b799-11e0-b684-00163e4c6b77',
                'user_login' => 'test-user-10',
                'user_password' => sha1( 'advanced-user' ),
                'user_first_name' => 'Advanced',
                'user_last_name' => 'User',
                'user_email_address' => 'advanced-user@openach.com',
                'user_security_question_1' => 'What is your favorite color?',
                'user_security_question_2' => 'What is capital of Assyria?',
                'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
                'user_security_answer_1' => 'Blue',
                'user_security_answer_2' => 'Nineveh',
                'user_security_answer_3' => 'African or European?',
                'user_status' => 'enabled',
        ),
        'sample5'=>array(
                'user_id' => '90383de8-b799-11e0-b684-00163e4c6b77',
                'user_login' => 'test-user-9',
                'user_password' => sha1( 'advanced-user' ),
                'user_first_name' => 'Advanced',
                'user_last_name' => 'User',
                'user_email_address' => 'advanced-user@openach.com',
                'user_security_question_1' => 'What is your favorite color?',
                'user_security_question_2' => 'What is capital of Assyria?',
                'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
                'user_security_answer_1' => 'Blue',
                'user_security_answer_2' => 'Nineveh',
                'user_security_answer_3' => 'African or European?',
                'user_status' => 'enabled',
        ),
        'sample6'=>array(
                'user_id' => '80383de8-b799-11e0-b684-00163e4c6b77',
                'user_login' => 'test-user-8',
                'user_password' => sha1( 'advanced-user' ),
                'user_first_name' => 'Advanced',
                'user_last_name' => 'User',
                'user_email_address' => 'advanced-user@openach.com',
                'user_security_question_1' => 'What is your favorite color?',
                'user_security_question_2' => 'What is capital of Assyria?',
                'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
                'user_security_answer_1' => 'Blue',
                'user_security_answer_2' => 'Nineveh',
                'user_security_answer_3' => 'African or European?',
                'user_status' => 'enabled',
        ),
        'sample7'=>array(
                'user_id' => '70383de8-b799-11e0-b684-00163e4c6b77',
                'user_login' => 'test-user-7',
                'user_password' => sha1( 'advanced-user' ),
                'user_first_name' => 'Advanced',
                'user_last_name' => 'User',
                'user_email_address' => 'advanced-user@openach.com',
                'user_security_question_1' => 'What is your favorite color?',
                'user_security_question_2' => 'What is capital of Assyria?',
                'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
                'user_security_answer_1' => 'Blue',
                'user_security_answer_2' => 'Nineveh',
                'user_security_answer_3' => 'African or European?',
                'user_status' => 'enabled',
        ),
        'sample8'=>array(
                'user_id' => '60383de8-b799-11e0-b684-00163e4c6b77',
                'user_login' => 'test-user-6',
                'user_password' => sha1( 'advanced-user' ),
                'user_first_name' => 'Advanced',
                'user_last_name' => 'User',
                'user_email_address' => 'advanced-user@openach.com',
                'user_security_question_1' => 'What is your favorite color?',
                'user_security_question_2' => 'What is capital of Assyria?',
                'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
                'user_security_answer_1' => 'Blue',
                'user_security_answer_2' => 'Nineveh',
                'user_security_answer_3' => 'African or European?',
                'user_status' => 'enabled',
        ),
        'sample9'=>array(
                'user_id' => '50383de8-b799-11e0-b684-00163e4c6b77',
                'user_login' => 'test-user-5',
                'user_password' => sha1( 'advanced-user' ),
                'user_first_name' => 'Advanced',
                'user_last_name' => 'User',
                'user_email_address' => 'advanced-user@openach.com',
                'user_security_question_1' => 'What is your favorite color?',
                'user_security_question_2' => 'What is capital of Assyria?',
                'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
                'user_security_answer_1' => 'Blue',
                'user_security_answer_2' => 'Nineveh',
                'user_security_answer_3' => 'African or European?',
                'user_status' => 'enabled',
        ),
        'sample10'=>array(
                'user_id' => '40383de8-b799-11e0-b684-00163e4c6b77',
                'user_login' => 'test-user-4',
                'user_password' => sha1( 'advanced-user' ),
                'user_first_name' => 'Advanced',
                'user_last_name' => 'User',
                'user_email_address' => 'advanced-user@openach.com',
                'user_security_question_1' => 'What is your favorite color?',
                'user_security_question_2' => 'What is capital of Assyria?',
                'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
                'user_security_answer_1' => 'Blue',
                'user_security_answer_2' => 'Nineveh',
                'user_security_answer_3' => 'African or European?',
                'user_status' => 'enabled',
        ),
        'sample11'=>array(
                'user_id' => '30383de8-b799-11e0-b684-00163e4c6b77',
                'user_login' => 'test-user-3',
                'user_password' => sha1( 'advanced-user' ),
                'user_first_name' => 'Advanced',
                'user_last_name' => 'User',
                'user_email_address' => 'advanced-user@openach.com',
                'user_security_question_1' => 'What is your favorite color?',
                'user_security_question_2' => 'What is capital of Assyria?',
                'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
                'user_security_answer_1' => 'Blue',
                'user_security_answer_2' => 'Nineveh',
                'user_security_answer_3' => 'African or European?',
                'user_status' => 'enabled',
        ),
        'sample12'=>array(
                'user_id' => '20383de8-b799-11e0-b684-00163e4c6b77',
                'user_login' => 'test-user-2',
                'user_password' => sha1( 'advanced-user' ),
                'user_first_name' => 'Advanced',
                'user_last_name' => 'User',
                'user_email_address' => 'advanced-user@openach.com',
                'user_security_question_1' => 'What is your favorite color?',
                'user_security_question_2' => 'What is capital of Assyria?',
                'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
                'user_security_answer_1' => 'Blue',
                'user_security_answer_2' => 'Nineveh',
                'user_security_answer_3' => 'African or European?',
                'user_status' => 'enabled',
        ),
        'sample13'=>array(
                'user_id' => '10383de8-b799-11e0-b684-00163e4c6b77',
                'user_login' => 'test-user-1',
                'user_password' => sha1( 'advanced-user' ),
                'user_first_name' => 'Advanced',
                'user_last_name' => 'User',
                'user_email_address' => 'advanced-user@openach.com',
                'user_security_question_1' => 'What is your favorite color?',
                'user_security_question_2' => 'What is capital of Assyria?',
                'user_security_question_3' => 'What is the air-speed velocity of an unladen swallow?',
                'user_security_answer_1' => 'Blue',
                'user_security_answer_2' => 'Nineveh',
                'user_security_answer_3' => 'African or European?',
                'user_status' => 'enabled',
        ),


);
